### ISSUE TITLE
Semicolons vs no (and potential need for ESLint) 

### ISSUE THREAD

**Issue by drschwabe** [drschwabe/coinos-tests#1]
@ahopk127 thanks for the [commit](https://github.com/coinos/coinos-tests/commit/1367d1cf65eff87767dd29686706251f16b34dda) !
 Appreciate your input.  And feel free to commit more. 

This particular commit however brings up an age old debate in JavaScript. 
I am of the camp that semicolons are cluttery and unnecessary.  Ie- one of JS benefits is that it can look clean and not like C++ 

that said, Im not necessarily opposed if there is a good reason.    And for functionality they are sometimes necessary; though there is only one case I have come across myself and that is involving browserify's handling of an anon async func in root global space in client side context.   

anyway, a better approach instead of adhoc adding or removing them would be using an [ESLint](https://eslint.org/) config and perhaps fleshing that out in a sep branch such that we can have all devs (ie- just you and me so far) on the same page with regards to coding standards on this repo (and then merging the final approved spec to master).   That way there is a coding standard formalized in a file and we can auto-run it to perform the necessary fixups - either before we commit or apart of a Github action.

**Comment by ahopk127** [comment]
To be honest, that was just a test commit - I just put it through `prettier` (I was testing both that and my ability to push to github) and committed.  I probably should have put that in the commit message.  Feel free to reverse my changes.  I've used languages with semicolons and without, and I'm new to JS so I don't have an opinion on this debate yet.

**Comment by drschwabe** [comment]
Cool!  Ya no worries.  This was a legit first commit dude.   No  need to rollback, since they aren't causing any issue. 

Prettier like ESLint also has a config file approach that could be used; ie- such that we can do a quick command to run it before committing; or integrate into an auto pipeline.  So maybe if you are interesetd in using it you could commit a `.prettierrc` file. 

Seems ESLint is more on the side of catching bugs, it can also omit/include semicolos so that is another alternative. 

https://prettier.io/docs/en/configuration.html
https://prettier.io/docs/en/comparison.html

For future commits, general etiqutte is to commit on a sep branch and PR ie- if it is something of a test commit or something you are unsure if the primary maintainer will approve or not - coinos-server and ui are a little different examples since they have a lot of activity on master so this isn't necessarily a hard rule - but for repos I am primary maintainer personally I prefer sep branches and PRs for new features/fixes.
